[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311"]

[build.nixpacksPlan.phases.start]
cmd = "python app.py"

[deploy]
startCommand = "python app.py"